spring:
  application:
    name: scm-saas
  datasource:
    url: jdbc:postgresql://localhost:5432/scm_master
    username: master_user
    password: master_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
cloud:
  config:
    uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    com.scm_saas.SCM_SaaS: DEBUG
  file:
    name: logs/scm-saas.log
data:
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
