spring:
  security:
    enabled: true
  devtools:
    restart:
      enabled: false
  application:
    name: scm-saas
  datasource:
    url: jdbc:postgresql://localhost:5432/scm_master
    username: master_user
    password: master_password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  config:
    import: configserver:http://localhost:8888
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    user: master_user
    password: master_password
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    clear-checksums: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
cloud:
  config:
    uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    liquibase: DEBUG
    root: INFO
    com.scm_saas.SCM_SaaS: DEBUG
    org:
      springframework:
        web:
          filter: DEBUG

  file:
    name: logs/scm-saas.log

data:
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

